version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: karnain_ai
      MYSQL_USER: karnain_user
      MYSQL_PASSWORD: K4rn41n#2026
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d